[tool.ruff]
line-length = 100
lint.select = ["E", "F", "I"]   # Errors, pyflakes, import checks
lint.ignore = ["E501"]          # lange regels mag black oplossen

[tool.black]
line-length = 100

[project]
license = { file = "LICENSE" }
classifiers = ["License :: Other/Proprietary License"]
